language: rust
cache: cargo
rust: stable

branches:
  except:
    - /^wip\/.*$/

env:
  global:
    - RUSTFLAGS="-D warnings"

before_install:
- rustup component add clippy
- rustup component add rustfmt

script:
- cargo fmt -- --check
- cargo clippy --all-targets
- cargo build
- cargo test
