version: 2
jobs:
  build:
    macos:
      xcode: "10.1.0"

    branches:
      ignore:
        - /^wip\/.*$/

    environment:
      RUSTFLAGS: "-D warnings"

    steps:
      - restore_cache:
          keys:
            - rust

      - run:
          name: Install Rust
          command: |
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            cat ~/.cargo/env >> $BASH_ENV
            source ~/.cargo/env
            cargo --version
            rustc --version
            rustup component add clippy
            rustup component add rustfmt

      - checkout
      - run: cargo fmt -- --check
      - run: cargo clippy --all-targets
      - run: cargo build
      - run: cargo test

      - save_cache:
          key: rust
          paths:
            - ~/.cargo
            - ~/.rustup
